services:
  leboncoinalert:
    image: leboncoinalert:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - .env